/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Metodos.MEtodo3y5Puntos;
import Metodos.Rosemberg;
import Metodos.Simpson;
import Metodos.Trapecio;
import Metodos.diferenciasAdelante;
import Metodos.diferenciasAtras;
import Metodos.diferenciasCentradas;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author robal
 */
public class Analisis05 extends javax.swing.JFrame {

    /**
     * Creates new form Analisis05
     */
    Trapecio t = new Trapecio();
    diferenciasAdelante da = new diferenciasAdelante();
    diferenciasAtras d = new diferenciasAtras();
    diferenciasCentradas c = new diferenciasCentradas();
    MEtodo3y5Puntos m = new MEtodo3y5Puntos();
    Rosemberg r = new Rosemberg();
    Simpson s = new Simpson();
    int n;
    int cal;
    JTextArea con = new JTextArea();
    DefaultTableModel ta = new DefaultTableModel(new Object[]{"h", "nivel 0", "nivel 1", "nivle 2", "nivel 3"}, 0);

    public Analisis05() {
        initComponents();
        this.setLocationRelativeTo(null);
        ver(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        deri = new javax.swing.JButton();
        integracion = new javax.swing.JButton();
        nombres = new javax.swing.JLabel();
        cmbfun = new javax.swing.JComboBox();
        integration = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        txq = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txta = new javax.swing.JTextField();
        txtb = new javax.swing.JTextField();
        tN = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_active__no.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_disabled__undo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 0, 30, 30));

        deri.setText("Derivación númerica");
        deri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deriActionPerformed(evt);
            }
        });
        getContentPane().add(deri, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        integracion.setText("Integración númerica");
        integracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                integracionActionPerformed(evt);
            }
        });
        getContentPane().add(integracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        nombres.setBackground(new java.awt.Color(204, 255, 255));
        nombres.setForeground(new java.awt.Color(153, 255, 255));
        nombres.setText(" MQ16001--------------------------------------AG16028");
        getContentPane().add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 300, 20));

        cmbfun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbfun.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbfunItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbfun, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 200, 30));

        integration.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        integration.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                integrationItemStateChanged(evt);
            }
        });
        getContentPane().add(integration, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, 30));

        txt.setEditable(false);
        txt.setColumns(20);
        txt.setRows(5);
        jScrollPane1.setViewportView(txt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 330, 170));

        txq.setForeground(new java.awt.Color(153, 255, 255));
        txq.setText("Que metodo desea utilizar?");
        getContentPane().add(txq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Valor de N:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));
        getContentPane().add(txta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));
        getContentPane().add(txtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        tN.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        tN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tNItemStateChanged(evt);
            }
        });
        tN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNKeyTyped(evt);
            }
        });
        getContentPane().add(tN, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void integracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_integracionActionPerformed
        // integración
        n = 2;
        cmbfun.removeAllItems();
        integration.removeAllItems();
        integration.addItem("SELECCIONE");
        cmbfun.addItem("SELECIONE");
        ver(true);
        cmbfun.addItem("sin(x)");
        cmbfun.addItem("x(e^x)");
        cmbfun.addItem("(sin(x))/x");
        cmbfun.addItem("(x^2)ln(x)");
        cmbfun.addItem("(x^2)sin(x)");
        cmbfun.addItem("1/(x^2 +1)^(1/2)");
        integration.setVisible(true);
        txq.setVisible(true);
        integration.addItem("Trapecio Simple");
        integration.addItem("Trapecio Compuesto");
        integration.addItem("Simpson 1/3 Simple");
        integration.addItem("Simpson 1/3 Compuesto");
        integration.addItem("Simpson 3/8 Simple");
        integration.addItem("Simpson 3/8 Compuesto");
        integration.addItem("Rosemberg");
    }//GEN-LAST:event_integracionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ver(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deriActionPerformed
        cmbfun.removeAllItems();
        n = 1;
        cmbfun.addItem("SELECIONE");
        ver(true);
        cmbfun.addItem("ln(x)tan(x)");
        cmbfun.addItem("(e^x)cos(x)");
        cmbfun.addItem("(e^(x^2))sin(x)");
        cmbfun.addItem("(x^3)(e^(x^2))+cos(x)");
        cmbfun.addItem("2(x^2)sin(x)");
        cmbfun.addItem("(3^x)cos(x)");
        cmbfun.addItem("(2x)(e^x)sin(x)");
        cmbfun.addItem("3(x^2)(e^x)");
        cmbfun.addItem("(e^x)sin(x)");


    }//GEN-LAST:event_deriActionPerformed

    private void cmbfunItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbfunItemStateChanged
        txt.setText("");
        cal = 0;
        tN.setSelectedIndex(0);
        if (cmbfun.getSelectedIndex() != 0) {
            switch (cmbfun.getSelectedIndex()) {
                case 1:
                    if (n == 1) {
                        txt.setText("Metodo de la Primera diferencia haci Adelante\n"
                                + "f ' (x) =  " + da.Der1P(1.2, 0.1, cmbfun.getSelectedItem().toString()));
                    } else {
                        tN.setVisible(true);
                        jLabel2.setVisible(true);
                        txta.setText("1");
                        txtb.setText("1.4");
                        integration.setSelectedIndex(0);
                    }
                    break;
                case 2:
                    if (n == 1) {
                        txt.setText("Metodo de la Primera diferencia haci Adelante\n"
                                + "f ' (x) = " + da.Der1P(0.5, 0.1, cmbfun.getSelectedItem().toString()));
                    } else {
                        tN.setVisible(true);
                        jLabel2.setVisible(true);
                        txta.setText("0");
                        txtb.setText("1.2");
                        integration.setSelectedIndex(0);
                    }
                    break;
                case 3:
                    if (n == 1) {
                        txt.setText("Metodo de la Primera diferencia haci Atras\n"
                                + "f ' (x) = " + d.Der1pAt(1, 0.1, cmbfun.getSelectedItem().toString()));
                    } else {
                        tN.setVisible(true);
                        jLabel2.setVisible(true);
                        txta.setText("-1");
                        txtb.setText("1");
                        integration.setSelectedIndex(0);
                    }
                    break;
                case 4:
                    if (n == 1) {
                        txt.setText("Metodo de los 3 puntos\n"
                                + "f ' (x) = " + m.for3(0.65, 0.2, cmbfun.getSelectedItem().toString()));
                    } else {
                        tN.setVisible(true);
                        jLabel2.setVisible(true);
                        txta.setText("2");
                        txtb.setText("3");
                        integration.setSelectedIndex(0);
                    }
                    break;
                case 5:
                    if (n == 1) {
                        txt.setText("Metodo de los 3 puntos\n"
                                + "f ' (x) = " + m.for3(1, 0.2, cmbfun.getSelectedItem().toString()));
                    } else {
                        tN.setVisible(true);
                        jLabel2.setVisible(true);
                        txta.setText("0");
                        txtb.setText("" + Math.PI);
                        integration.setSelectedIndex(0);
                    }
                    break;
                case 6:
                    if (n == 1) {
                        txt.setText("Metodo de Segunda diferencia Centrada\n"
                                + "f ' (x) = " + c.Der1sC(0.8, 0.2, cmbfun.getSelectedItem().toString()));
                    } else {
                        tN.setVisible(true);
                        jLabel2.setVisible(true);
                        txta.setText("0");
                        txtb.setText("" + Math.PI);
                        integration.setSelectedIndex(0);
                    }
                    break;
                case 7:
                    if (n == 1) {
                        txt.setText("La primera derivada es: \n"
                                + "f ' (x) = " + c.Der1sC(0.5, 0.5, cmbfun.getSelectedItem().toString()) + "\n\n"
                                + "La Segunda derivada es:\n"
                                + "f '' (x) = " + c.Der2sC(0.5, 0.5, cmbfun.getSelectedItem().toString()));
                    }
                    break;
                case 8:
                    if (n == 1) {
                        con.setText("CALCULANDO LAS DERIVADA PARA \n"
                                + "X=0.2, H=0.05\n"
                                + "Primera Derivada\nprimera diferencia Centrada: \n"
                                + "f ' (x) = " + c.Der1pC(0.2, 0.05, cmbfun.getSelectedItem().toString()) + "\n"
                                + "Segunda Diferencia Centrada\n"
                                + "f ' (x) = " + c.Der1sC(0.2, 0.05, cmbfun.getSelectedItem().toString()) + "\n"
                                + "La Segunda derivada\nprimera diferencia Centrada\n"
                                + "f '' (x) = " + c.Der2pC(0.2, 0.05, cmbfun.getSelectedItem().toString())
                                + "\nSegunda diferencia Centrada\n"
                                + "f '' (x) = " + c.Der2sC(0.2, 0.05, cmbfun.getSelectedItem().toString())
                                + "\n---CALCULANDO DERIVADAS PARA---\nX=0.5 H=0.1\n"
                                + "Resultados:\n"
                                + "Metodo de los 3 puntos: " + m.for3(0.5, 0.1, cmbfun.getSelectedItem().toString()) + "\n"
                                + "Metodo de los 5 puntos\n primera diferencia: " + m.for5(0.5, 0.1, cmbfun.getSelectedItem().toString(), 1) + "\n"
                                + "segunda diferencia: " + m.for5(0.5, 0.1, cmbfun.getSelectedItem().toString(), 2) + "\n"
                                + "--CONCLUSION--\n"
                                + "Podemos observar que para el calculo\n"
                                + "de la derivadas es mucho mas \n"
                                + "preciso el metodo de los 5 puntos");
                        txt.setText(con.getText());
                    }
                    break;
                case 9:
                    if (n == 1) {
                        txt.setText("Metodo de los 3 puntos: " + m.for3(1.3, 0.1, cmbfun.getSelectedItem().toString()) + "\n"
                                + "Metodo de los 5 puntos\nprimera diferencia: " + m.for5(1.3, 0.1, cmbfun.getSelectedItem().toString(), 1) + "\n"
                                + "segunda diferencia: " + m.for5(1.3, 0.1, cmbfun.getSelectedItem().toString(), 2));
                        txt.setText(con.getText());
                    }
                    break;
            }
        } else {
            integration.setEnabled(false);
            integration.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmbfunItemStateChanged

    private void integrationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_integrationItemStateChanged
        con.setText("");
        txt.setText("");
            switch (integration.getSelectedIndex()) {
            case 1:
                tN.setEditable(false);
                con.setText("" + t.TrapecioSim(Double.parseDouble(txta.getText()), Double.parseDouble(txtb.getText()), cmbfun.getSelectedItem().toString()));
                break;
            case 2:
                con.setText("" + t.TrapecioCom(Double.parseDouble(txta.getText()), Double.parseDouble(txtb.getText()), cmbfun.getSelectedItem().toString(), tN.getSelectedIndex()));
                break;
            case 3:
                tN.setEditable(false);
                con.setText("" + s.Simp1S(Double.parseDouble(txta.getText()), Double.parseDouble(txtb.getText()), cmbfun.getSelectedItem().toString()));
                break;
            case 4:
                con.setText("" + s.Sim1Co(Double.parseDouble(txta.getText()), Double.parseDouble(txtb.getText()), cmbfun.getSelectedItem().toString(), tN.getSelectedIndex()));
                break;
            case 5:
                tN.setEditable(false);
                con.setText("" + s.Sim3S(Double.parseDouble(txta.getText()), Double.parseDouble(txtb.getText()), cmbfun.getSelectedItem().toString()));
                break;
            case 6:
                con.setText("" + s.Sim3Co(Double.parseDouble(txta.getText()), Double.parseDouble(txtb.getText()), cmbfun.getSelectedItem().toString(), tN.getSelectedIndex()));
                break;
            case 7:
                con= r.Ros(Double.parseDouble(txta.getText()), Double.parseDouble(txtb.getText()), cmbfun.getSelectedItem().toString(),0.2, tN.getSelectedIndex());
                break;
        }
        txt.setText(con.getText());
    }//GEN-LAST:event_integrationItemStateChanged

    private void tNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNKeyTyped
        
    }//GEN-LAST:event_tNKeyTyped

    private void tNItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tNItemStateChanged
        if (tN.getSelectedIndex()!=0) {
            integration.setEnabled(true);
            integration.setSelectedIndex(0);
        }else{
            integration.setEnabled(false);
        }
    }//GEN-LAST:event_tNItemStateChanged
    public final void ver(boolean x) {
        cmbfun.setVisible(x);
        integracion.setVisible(!x);
        deri.setVisible(!x);
        nombres.setVisible(!x);
        txt.setVisible(x);
        jScrollPane1.setVisible(x);
        integration.setVisible(false);
        txq.setVisible(false);
        tN.setVisible(false);
        txta.setVisible(false);
        txtb.setVisible(false);
        jLabel2.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analisis05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analisis05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analisis05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analisis05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analisis05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbfun;
    private javax.swing.JButton deri;
    private javax.swing.JButton integracion;
    private javax.swing.JComboBox integration;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombres;
    private javax.swing.JComboBox tN;
    private javax.swing.JLabel txq;
    private javax.swing.JTextArea txt;
    private javax.swing.JTextField txta;
    private javax.swing.JTextField txtb;
    // End of variables declaration//GEN-END:variables
}
